/** Strict schema shown to models and enforced for newly generated surfaces. */
export const RENDER_CARDS_INPUT_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["messages"],
  properties: {
    messages: {
      type: "array",
      minItems: 1,
      items: {
        type: "object",
        additionalProperties: false,
        required: ["version"],
        properties: {
          version: { const: "v1.0" },
          createSurface: {
            type: "object",
            additionalProperties: false,
            required: ["surfaceId", "catalogId"],
            properties: {
              surfaceId: { type: "string", minLength: 1 },
              catalogId: { const: "urn:openneko:catalog:work:v2" },
              surfaceProperties: { type: "object" },
              sendDataModel: { type: "boolean" },
              components: { $ref: "#/$defs/components" },
              dataModel: { type: "object" },
            },
          },
          updateComponents: {
            type: "object",
            additionalProperties: false,
            required: ["surfaceId", "components"],
            properties: {
              surfaceId: { type: "string", minLength: 1 },
              components: { $ref: "#/$defs/components" },
            },
          },
          updateDataModel: {
            type: "object",
            additionalProperties: false,
            required: ["surfaceId"],
            properties: {
              surfaceId: { type: "string", minLength: 1 },
              path: { type: "string" },
              value: {},
            },
          },
          deleteSurface: {
            type: "object",
            additionalProperties: false,
            required: ["surfaceId"],
            properties: { surfaceId: { type: "string", minLength: 1 } },
          },
        },
        oneOf: [
          { required: ["createSurface"] },
          { required: ["updateComponents"] },
          { required: ["updateDataModel"] },
          { required: ["deleteSurface"] },
        ],
      },
    },
  },
  $defs: {
    components: {
      type: "array",
      minItems: 1,
      items: {
        type: "object",
        required: ["id", "component"],
        properties: {
          id: { type: "string", minLength: 1 },
          component: { type: "string", minLength: 1 },
        },
      },
    },
  },
} as const;

/** Catalog supplied with the render_cards tool for conversational web surfaces. */
export const RENDER_CARDS_DESCRIPTION = [
  "Render a structured, interactive answer with the A2UI v1.0 protocol.",
  "Use this for configuration forms, result tables, findings, KPIs, and useful next actions.",
  "Send an array of protocol messages. New surfaces use one createSurface message with",
  '`version:"v1.0"`, catalogId `urn:openneko:catalog:work:v2`, globally unique surfaceId,',
  "components, and an initial dataModel. Every surface has a component with id `root`.",
  "Property bindings use `{ path: \"/json/pointer\" }`.",
  "",
  "Catalog components:",
  "- Answer: answer frame. Props title, subtitle?, eyebrow?, children[].",
  "- Markdown: narrative markdown. Prop text.",
  "- Text: compact text. Props text, variant? (`body` or `caption`).",
  "- MetricCard: KPI. Props metricId, source, mood, text, metric, label, detail, chartType, chartData.",
  "- Table: structured results. Props columns[{key,label,align?}], rows[], caption?.",
  "- Callout: operational status/takeaway. Props mood (`good`|`watch`|`act`), title?, text.",
  "- Section: titled group. Props title, children[], collapsible?, defaultOpen?.",
  "- Row / Column: layout containers. Props children[], justify?, align?.",
  "- Tabs: tabbed detail. Props tabs[{title,child}].",
  "- TextField: bound input. Props label, value?, placeholder?, variant?",
  "  (`shortText`|`longText`|`number`|`obscured`).",
  "- CheckBox: bound boolean. Props label, value.",
  "- ChoicePicker: bound string-array selection. Props label?, options[{label,value}],",
  "  value, variant? (`mutuallyExclusive`|`multipleSelection`), displayStyle?.",
  "- Button: action button. Props child (a Text component id), variant, action.event.",
  "- Choice: quick follow-up buttons. Props options[{label,prompt,mood?}].",
  "- Divider: separator. Props label?.",
  "",
  "For editable configuration, bind each field to the dataModel. A submit Button uses",
  "`action.event.name` plus context `{ prompt: <clear next instruction>, values: {path:\"/form\"} }`.",
  "The operator's submitted values arrive in the next turn. Validate them, then use the",
  "appropriate proposal tool so the existing approval policy remains the commit boundary.",
  "Use `secretRef` names in forms for credentials.",
  "",
  "Example — editable source proposal:",
  "[",
  '  {"version":"v1.0","createSurface":{',
  '    "surfaceId":"source-form-<unique>","catalogId":"urn:openneko:catalog:work:v2",',
  '    "dataModel":{"form":{"name":"","kind":["database"],"host":"","port":5432,"dbname":"","user":"","secretRef":""}},',
  '    "components":[',
  '      {"id":"root","component":"Answer","eyebrow":"GRAPHJIN CONFIG","title":"Add a source","subtitle":"Review the connection metadata, then file an approval proposal.","children":["note","fields","submit"]},',
  '      {"id":"note","component":"Callout","mood":"watch","title":"Approval required","text":"Submitting creates a configuration proposal for admin review."},',
  '      {"id":"fields","component":"Column","children":["name","kind","network","database"]},',
  '      {"id":"name","component":"TextField","label":"Source name","value":{"path":"/form/name"},"placeholder":"warehouse"},',
  '      {"id":"kind","component":"ChoicePicker","label":"Source kind","options":[{"label":"Database","value":"database"},{"label":"GraphJin","value":"graphjin"},{"label":"API","value":"api"}],"value":{"path":"/form/kind"},"variant":"mutuallyExclusive"},',
  '      {"id":"network","component":"Row","children":["host","port"]},',
  '      {"id":"host","component":"TextField","label":"Host","value":{"path":"/form/host"},"placeholder":"db.internal"},',
  '      {"id":"port","component":"TextField","label":"Port","value":{"path":"/form/port"},"variant":"number"},',
  '      {"id":"database","component":"Row","children":["dbname","user","secretRef"]},',
  '      {"id":"dbname","component":"TextField","label":"Database","value":{"path":"/form/dbname"}},',
  '      {"id":"user","component":"TextField","label":"User","value":{"path":"/form/user"}},',
  '      {"id":"secretRef","component":"TextField","label":"Stored secret name","value":{"path":"/form/secretRef"},"placeholder":"warehouse-password"},',
  '      {"id":"submitLabel","component":"Text","text":"Review proposal"},',
  '      {"id":"submit","component":"Button","child":"submitLabel","variant":"primary","action":{"event":{"name":"submit_source_config","context":{"prompt":"Review these values and file a register_source configuration proposal.","values":{"path":"/form"}}}}}',
  "    ]",
  "  }}",
  "]",
].join("\n");
