/**
 * ST1 — the A2UI/BriefingCard catalog lives on the `render_cards` TOOL
 * description, not in the agent's base prompt. The channel that supplies
 * the tool supplies the catalog (web today; other surfaces ship their own
 * renderer), so the base prompt stays channel-neutral. Both backends use
 * this text: claude via the neko_ui SDK MCP server, hermes via the stdio
 * render stub's tools/list.
 */
export const RENDER_CARDS_DESCRIPTION = [
  "Render structured Neko cards inline in the chat using the A2UI v0.9 protocol.",
  "Prefer this over markdown when you have numeric findings, KPIs, or trends.",
  "",
  "Pass an ARRAY of A2UI v0.9 protocol messages — each must have",
  '`version: "v0.9"` plus exactly one of: `createSurface`, `updateComponents`,',
  "`updateDataModel`, `deleteSurface`. Bare component objects (e.g.",
  '`{ "type": "kpi_group", ... }`) are rejected — they MUST be wrapped in',
  "an `updateComponents` envelope.",
  "",
  "Catalog (catalogId `urn:app:catalog:briefing:v1`):",
  "  - `Markdown` — prose block. Use for ANY narrative text — your response",
  "    prose lives here, never outside the tool call. Props: text (markdown",
  "    string; supports headings, lists, tables, code blocks).",
  "  - `Briefing` — root container. Props: greeting, subtitle, role, children[].",
  "    Always list EVERY body component's id in `children`, in display order —",
  "    both Markdown narrative blocks and BriefingCards. The body renders from",
  "    this list.",
  "  - `BriefingCard` — KPI card with optional chart. Required props:",
  "    metricId (any string for ad-hoc cards, e.g. 'chat-1'),",
  '    source ("chat" for ad-hoc rendering),',
  '    mood ("good" | "watch" | "act"),',
  "    text (1-sentence headline), metric (e.g. '$498,376'),",
  "    label (e.g. 'Total Profit'), detail (1-3 sentences),",
  '    chartType ("kpi" | "line" | "bar" | "area" | "donut"),',
  "    chartData (array of `{ d: string, v: number, t?: number }`,",
  '    or `[]` when chartType="kpi").',
  "  - `Table` — tabular data. Props: columns (array of",
  '    `{ key, label, align? }`), rows (array of objects keyed by column key),',
  "    caption?. Prefer this over a markdown table for real result sets.",
  "  - `Callout` — a mood-tinted takeaway/recommendation (not a KPI tile).",
  '    Props: mood ("good"|"watch"|"act"), title?, text (markdown).',
  "  - `Section` — a titled group. Props: title, children[] (ids),",
  "    collapsible? (folds long supporting detail), defaultOpen?.",
  "  - `Choice` — INTERACTIVE follow-up buttons. Props: options (array of",
  "    `{ label, prompt, mood? }`). Clicking an option sends its `prompt`",
  "    back as the next turn. Offer 2-4 sharp drill-downs the user will",
  "    likely want next, instead of ending flat.",
  "  - `Divider` — a separator. Props: label?.",
  "",
  "Compose freely: lead with a Markdown or Callout takeaway, show numbers as",
  "BriefingCards or a Table, group supporting detail in a Section, and close",
  "with a Choice of next steps. Reach past the briefing skeleton when the",
  "answer calls for it — every component id you create must appear in the",
  "root's `children` in display order.",
  "",
  "Typical message sequence:",
  "  1. createSurface (once)",
  "  2. updateComponents with a `Briefing` root whose `children` lists every",
  "     other component id (Markdown + BriefingCard) in display order",
  "",
  "Example (one KPI card, no chart):",
  "[",
  '  { "version":"v0.9", "createSurface":{ "surfaceId":"s1",',
  '    "catalogId":"urn:app:catalog:briefing:v1" } },',
  '  { "version":"v0.9", "updateComponents":{ "surfaceId":"s1", "components":[',
  '    { "id":"root", "component":"Briefing", "greeting":"Top product",',
  '      "subtitle":"All stores", "role":"CEO", "children":["c1"] },',
  '    { "id":"c1", "component":"BriefingCard", "metricId":"chat-1",',
  '      "source":"chat", "mood":"good", "text":"Mountain-200 Silver leads",',
  '      "metric":"$498,376", "label":"Total Profit",',
  '      "detail":"$3.19M revenue − $2.70M cost on 2,130 units sold.",',
  '      "chartType":"kpi", "chartData":[] }',
  "  ]}}",
  "]",
  "",
  "Example (narrative + KPI — `children` lists the Markdown blocks AND the card):",
  "[",
  '  { "version":"v0.9", "createSurface":{ "surfaceId":"s1",',
  '    "catalogId":"urn:app:catalog:briefing:v1" } },',
  '  { "version":"v0.9", "updateComponents":{ "surfaceId":"s1", "components":[',
  '    { "id":"root", "component":"Briefing", "greeting":"SLA Watch",',
  '      "subtitle":"Pending orders past SLA", "role":"Operations Specialist",',
  '      "children":["intro","c1","details"] },',
  '    { "id":"intro", "component":"Markdown",',
  '      "text":"The **Slow-Ship** workflow flags orders pending past the 5-day SLA." },',
  '    { "id":"c1", "component":"BriefingCard", "metricId":"chat-1",',
  '      "source":"chat", "mood":"act", "text":"SLA breaches are critical",',
  '      "metric":"10,878", "label":"Breaching Orders",',
  '      "detail":"98% of the pending queue is past the 5-day SLA.",',
  '      "chartType":"kpi", "chartData":[] },',
  '    { "id":"details", "component":"Markdown",',
  '      "text":"### How it works — runs daily at 8:30 AM UTC; alerts when >10 orders breach." }',
  "  ]}}",
  "]",
  "",
  "Example (Callout + Table + interactive Choice):",
  "[",
  '  { "version":"v0.9", "createSurface":{ "surfaceId":"s1",',
  '    "catalogId":"urn:app:catalog:briefing:v1" } },',
  '  { "version":"v0.9", "updateComponents":{ "surfaceId":"s1", "components":[',
  '    { "id":"root", "component":"Briefing", "greeting":"Top 3 territories",',
  '      "subtitle":"Revenue, trailing 12 months", "role":"CRO",',
  '      "children":["take","tbl","next"] },',
  '    { "id":"take", "component":"Callout", "mood":"good", "title":"Takeaway",',
  '      "text":"Southwest leads at **$4.7M**, 18% ahead of the next region." },',
  '    { "id":"tbl", "component":"Table",',
  '      "columns":[{"key":"region","label":"Region"},',
  '        {"key":"rev","label":"Revenue","align":"right"}],',
  '      "rows":[{"region":"Southwest","rev":"$4.7M"},',
  '        {"region":"Northwest","rev":"$4.0M"},{"region":"Canada","rev":"$3.1M"}] },',
  '    { "id":"next", "component":"Choice", "options":[',
  '      {"label":"Break down Southwest by product","prompt":"Break down Southwest revenue by product category."},',
  '      {"label":"Show the 12-month trend","prompt":"Show the monthly revenue trend for the top 3 territories."}] }',
  "  ]}}",
  "]",
].join("\n");
