query MagentoAverageOrderValue($from: String!, $to: String!, $storeIds: [Int!]) {
  sales_invoice(where: {and: [{created_at: {gte: $from}}, {created_at: {lt: $to}}], store_id: {in: $storeIds}}) {
    invoiced: sum_base_grand_total
  }
  sales_creditmemo(where: {and: [{created_at: {gte: $from}}, {created_at: {lt: $to}}], store_id: {in: $storeIds}}) {
    refunded: sum_base_grand_total
  }
  invoiced_orders: sales_order(where: {and: [{created_at: {gte: $from}}, {created_at: {lt: $to}}], store_id: {in: $storeIds}, base_total_invoiced: {gt: 0}}) {
    count: count_entity_id
  }
}
