query MagentoDataFreshness($from: String!) {
  sales_order(where: {created_at: {gte: $from}}, order_by: {created_at: desc}, limit: 1) {
    newest_order_at: created_at
  }
  cron_schedule(where: {created_at: {gte: $from}, status: {eq: "success"}}, order_by: {finished_at: desc}, limit: 1) {
    newest_successful_cron_at: finished_at
  }
}
