query MagentoFulfillmentAge($from: String!, $storeIds: [Int!]) {
  sales_order(
    where: {
      store_id: {in: $storeIds}
      created_at: {gte: $from}
      state: {nin: ["canceled", "closed", "complete"]}
      base_total_paid: {gt: 0}
    }
    order_by: {created_at: asc}
    limit: 5000
  ) {
    entity_id
    created_at
  }
}
