query MagentoOrdersPlaced($from: String!, $to: String!, $storeIds: [Int!]) {
  sales_order(where: {and: [{created_at: {gte: $from}}, {created_at: {lt: $to}}], store_id: {in: $storeIds}}) {
    orders: count_entity_id
  }
}
