query MagentoWatchRefundCancellation($from: String!, $storeIds: [Int!]) {
  sales_invoice(where: {created_at: {gte: $from}, store_id: {in: $storeIds}}) { invoiced: sum_base_grand_total }
  sales_creditmemo(where: {created_at: {gte: $from}, store_id: {in: $storeIds}}) { refunded: sum_base_grand_total }
  all_orders: sales_order(where: {created_at: {gte: $from}, store_id: {in: $storeIds}}) { count: count_entity_id }
  cancelled_orders: sales_order(where: {created_at: {gte: $from}, store_id: {in: $storeIds}, state: {eq: "canceled"}}) { count: count_entity_id }
}
