import { validateRecordIdentifier } from "../src/naming";
import type { RecordsGraphjinPolicyModel } from "../src/policy/graphjin";

const id = validateRecordIdentifier;

export function recordsPolicyFixture(): RecordsGraphjinPolicyModel {
  return {
    orgId: "org-a",
    catalog: [
      {
        schema: id("engine"),
        name: id("actor"),
        columns: [id("org_id"), id("user_id"), id("role")],
      },
      {
        schema: id("engine"),
        name: id("recycle_record"),
        columns: [
          id("org_id"),
          id("app_id"),
          id("object_api_name"),
          id("scope_key"),
          id("visibility"),
          id("record_id"),
          id("record_name"),
          id("owner_user_id"),
          id("deleted_at"),
          id("deleted_by"),
          id("deletion_action_request_id"),
        ],
      },
      {
        schema: id("engine"),
        name: id("identity_map"),
        columns: [
          id("org_id"),
          id("source_instance_id"),
          id("app_id"),
          id("source_user_id"),
          id("source_email"),
          id("source_email_normalized"),
          id("source_name"),
          id("source_is_active"),
          id("app_user_id"),
          id("status"),
          id("linked_at"),
          id("updated_at"),
        ],
      },
      {
        schema: id("engine"),
        name: id("record_change_log"),
        columns: [
          id("id"),
          id("org_id"),
          id("app_id"),
          id("object_api_name"),
          id("record_id"),
          id("action"),
          id("actor_user_id"),
          id("action_request_id"),
          id("mutation_id"),
          id("operation_seq"),
          id("changes"),
          id("at"),
          id("owner_user_id"),
        ],
      },
      {
        schema: id("public"),
        name: id("crm__account"),
        columns: [
          id("id"),
          id("org_id"),
          id("name"),
          id("industry"),
          id("owner_user_id"),
          id("nk_created_at"),
          id("nk_created_by"),
          id("nk_updated_at"),
          id("nk_updated_by"),
          id("nk_action_request_id"),
          id("nk_mutation_id"),
          id("nk_deleted_at"),
        ],
      },
      {
        schema: id("public"),
        name: id("crm__contact"),
        columns: [
          id("id"),
          id("org_id"),
          id("name"),
          id("owner_user_id"),
          id("nk_updated_at"),
          id("nk_deleted_at"),
        ],
      },
      {
        schema: id("public"),
        name: id("crm__legacy"),
        columns: [id("id"), id("org_id"), id("name"), id("nk_deleted_at")],
      },
      {
        schema: id("public"),
        name: id("orphan_table"),
        columns: [id("id"), id("secret")],
      },
    ],
    apps: [{ orgId: "org-a", appId: "crm", status: "active" }],
    objects: [
      {
        id: "object-account",
        orgId: "org-a",
        appId: "crm",
        apiName: id("account"),
        tableSchema: id("public"),
        tableName: id("crm__account"),
        nameField: id("name"),
        visibility: "org",
        archived: false,
      },
      {
        id: "object-contact",
        orgId: "org-a",
        appId: "crm",
        apiName: id("contact"),
        tableSchema: id("public"),
        tableName: id("crm__contact"),
        nameField: id("name"),
        visibility: "owner",
        archived: false,
      },
      {
        id: "object-legacy",
        orgId: "org-a",
        appId: "crm",
        apiName: id("legacy"),
        tableSchema: id("public"),
        tableName: id("crm__legacy"),
        nameField: id("name"),
        visibility: "org",
        archived: true,
      },
    ],
    fields: [
      { objectId: "object-account", columnName: id("name"), archived: false },
      { objectId: "object-account", columnName: id("industry"), archived: true },
      { objectId: "object-contact", columnName: id("name"), archived: false },
      { objectId: "object-legacy", columnName: id("name"), archived: false },
    ],
    permissions: [
      {
        appId: "crm",
        role: "member",
        objectApiName: id("account"),
        canRead: true,
        canCreate: true,
        canUpdate: true,
        canDelete: false,
      },
      {
        appId: "crm",
        role: "admin",
        objectApiName: id("account"),
        canRead: true,
        canCreate: true,
        canUpdate: true,
        canDelete: true,
      },
      {
        appId: "crm",
        role: "member",
        objectApiName: id("contact"),
        canRead: true,
        canCreate: true,
        canUpdate: true,
        canDelete: true,
      },
      {
        appId: "crm",
        role: "admin",
        objectApiName: id("contact"),
        canRead: true,
        canCreate: true,
        canUpdate: true,
        canDelete: true,
      },
    ],
  };
}
