import type { MagentoPackAdminFixture } from "./MagentoPackAdmin";

const defaultCaps = {
  maxRowsPerChangeset: 25,
  maxDailyAutoActions: 5,
  skuCooldownSeconds: 3600,
};

export const MAGENTO_VISUAL_FIXTURE: MagentoPackAdminFixture = {
  status: {
    packId: "magento",
    version: "2.0.0",
    status: "installed",
    readiness: {},
    installedAt: "2026-08-27T09:15:00.000Z",
    lastError: null,
  },
  doctor: {
    packId: "magento",
    status: "ready",
    checks: [
      {
        id: "analytics",
        status: "ready",
        detail: "MariaDB reporting access is healthy and limited to read-only queries.",
      },
      {
        id: "changes-catalog",
        status: "ready",
        detail: "Approved catalog changes are available and follow the limits below.",
      },
      {
        id: "changes-customers",
        status: "optional",
        detail: "Customer changes are currently view only.",
      },
    ],
  },
  management: {
    controls: [
      {
        domain: "catalog",
        automationEligible: true,
        enabled: true,
        autoExecute: true,
        readiness: "ready",
        readinessReason: null,
        readinessMessage: "Approved catalog changes are available.",
        caps: { ...defaultCaps, maxPriceDeltaPercent: 10 },
      },
      {
        domain: "content",
        automationEligible: true,
        enabled: true,
        autoExecute: false,
        readiness: "ready",
        readinessReason: null,
        readinessMessage: "Approved content changes are available.",
        caps: defaultCaps,
      },
      {
        domain: "customers",
        automationEligible: false,
        enabled: false,
        autoExecute: false,
        readiness: "optional",
        readinessReason: "domain_disabled",
        readinessMessage: "View only. Customer changes were disabled by an administrator.",
        caps: defaultCaps,
      },
      {
        domain: "inventory",
        automationEligible: true,
        enabled: true,
        autoExecute: false,
        readiness: "ready",
        readinessReason: null,
        readinessMessage: "Approved inventory changes are available.",
        caps: defaultCaps,
      },
      {
        domain: "orders",
        automationEligible: false,
        enabled: true,
        autoExecute: false,
        readiness: "ready",
        readinessReason: null,
        readinessMessage: "Approved order changes are available.",
        caps: defaultCaps,
      },
      {
        domain: "promotions",
        automationEligible: true,
        enabled: true,
        autoExecute: false,
        readiness: "ready",
        readinessReason: null,
        readinessMessage: "Approved promotion changes are available.",
        caps: {
          ...defaultCaps,
          maxDiscountPercent: 20,
          maxCouponCount: 100,
          maxProjectedExposure: 5000,
        },
      },
    ],
    rules: [
      {
        id: "rule-1",
        name: "Low-stock price correction",
        instruction: "Correct a product price only when the catalog source confirms the current value.",
        domain: "catalog",
        actionKind: "magento.manage_catalog",
        dailyCap: 5,
        cooldownSeconds: 3600,
        enabled: true,
        suspendedReason: null,
        isTest: false,
      },
      {
        id: "rule-test",
        name: "Local acceptance internal-run",
        instruction: "Exercise an internal acceptance path.",
        domain: "catalog",
        actionKind: "magento.manage_catalog",
        dailyCap: 1,
        cooldownSeconds: 0,
        enabled: false,
        suspendedReason: "suspended_by_admin",
        isTest: true,
      },
    ],
    changesets: [],
    handoffs: [],
    activity: [
      {
        id: "activity-price-reverted",
        kind: "change",
        title: "Prices restored",
        description: "Restored the original prices for 2 products.",
        outcome: "reverted",
        outcomeLabel: "Reverted",
        affectedCount: 2,
        source: "requested_change",
        sourceLabel: "Requested change",
        isTest: false,
        occurredAt: "2026-08-28T16:04:13.742Z",
        currentState: "No current price change",
        technical: {
          reference: "eaf3ad95-18e9-440b-9f14-6c3fd16ac48f",
          area: "Catalog",
          operation: "product_bulk_update",
          execution: "controlled_automation_eligible",
          originalRequest: "Seasonal two-product price correction",
          bulkReference: "bulk-0183",
          inverseOfReference: "0837187c-192f-4ed2-b9fc-eea65422dd35",
        },
      },
      {
        id: "activity-promotion-awaiting",
        kind: "change",
        title: "Promotion update awaiting approval",
        description: "An administrator needs to review this change before anything is updated in Magento.",
        outcome: "awaiting_approval",
        outcomeLabel: "Awaiting approval",
        affectedCount: 1,
        source: "requested_change",
        sourceLabel: "Requested change",
        isTest: false,
        occurredAt: "2026-08-28T15:35:00.000Z",
        currentState: "Nothing changed yet",
        technical: {
          reference: "42f655b4-3624-4054-9ba8-d38394867cd7",
          area: "Promotions",
          operation: "sales_rule_update",
          execution: "approval_required",
          originalRequest: "Weekend promotion adjustment",
          bulkReference: null,
          inverseOfReference: null,
        },
      },
      {
        id: "activity-test-content",
        kind: "change",
        title: "Content restored",
        description: "Restored the original content for 1 content block.",
        outcome: "reverted",
        outcomeLabel: "Reverted",
        affectedCount: 1,
        source: "test",
        sourceLabel: "Local test",
        isTest: true,
        occurredAt: "2026-08-28T14:10:00.000Z",
        currentState: "No current content change",
        technical: {
          reference: "0f8c6f6e-c41c-48ab-9466-d8149f5cc72c",
          area: "Content",
          operation: "cms_block_update",
          execution: "controlled_automation_eligible",
          originalRequest: "Local acceptance content check",
          bulkReference: null,
          inverseOfReference: "740da2f2-a28f-4f28-8c58-fe45d6934331",
        },
      },
    ],
    handoffOnly: {
      executePath: false,
      handoffKinds: [
        "online_refund",
        "return_approval",
        "financial_configuration",
        "store_credit_over_cap",
      ],
    },
  },
};
